apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    srv: api
spec:
  selector:
    srv: api
  type: NodePort
  ports:
   - name: mq
     port: 1414
     nodePort: 30005
   - name: mq-metrics
     port: 9157
     nodePort: 30006
   - name: ace-admin
     port: 7600
     nodePort: 30007
   - name: ace-http
     port: 7800
     nodePort: 30008
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    srv: api
  name: ace
spec:
  containers:
    - name: myace
      image: ibmcom/ace:11.0.0.0
      imagePullPolicy: Always
      stdin: true
      tty: true
      #command: ["/usr/bin/python3"]
      #args: ["ocr_server.py"]
      env:
      - name: LICENSE
        value: accept
    - name: mq
      image: ibmcom/mq #ibm-messaging/mq-container
      imagePullPolicy: Always
      env:
      - name: LICENSE
        value: accept
      - name: MQ_QMGR_NAME
        value: osipi
